//! Signal detection types for the CDC Action Zone strategy.
//!
//! The strategy (piriya33, `TradingView`) generates buy/sell signals on `EMA(12)`/`EMA(26)`
//! crossovers. Strength indicators (RSI, volume, trend) provide context but do not
//! gate alert delivery.

pub mod cdc_zone;
pub mod indicators;

use serde::{Deserialize, Serialize};

/// Direction of a detected EMA crossover.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum SignalType {
    Buy,
    Sell,
}

/// Market zone classification based on the relationship between price and EMAs.
///
/// Strong zones indicate price alignment with the EMA direction.
/// Weak zones indicate price has crossed back between the two EMAs.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Zone {
    /// `close > EMA(12) > EMA(26)` — strong upward momentum.
    Bull,
    /// `EMA(12) > EMA(26)` but `close < EMA(12)` — momentum fading.
    WeakBull,
    /// `close < EMA(12) < EMA(26)` — strong downward momentum.
    Bear,
    /// `EMA(12) < EMA(26)` but `close > EMA(12)` — selling pressure easing.
    WeakBear,
}

impl Zone {
    pub fn label(self) -> &'static str {
        match self {
            Self::Bull => "Bull (Strong)",
            Self::WeakBull => "Weak Bull",
            Self::Bear => "Bear (Strong)",
            Self::WeakBear => "Weak Bear",
        }
    }
}

impl std::fmt::Display for SignalType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Buy => write!(f, "BUY"),
            Self::Sell => write!(f, "SELL"),
        }
    }
}

/// A fully-resolved CDC Action Zone signal with supporting indicator context.
///
/// Generated by [`cdc_zone::analyze`] when an EMA crossover occurs on the most
/// recent candle. Strength fields are informational and do not influence alert delivery.
#[derive(Debug, Clone)]
#[allow(clippy::struct_field_names)]
pub struct Signal {
    pub symbol: String,
    pub signal_type: SignalType,
    pub zone: Zone,
    pub price: f64,
    pub fast_ema: f64,
    pub slow_ema: f64,
    /// RSI(14) value; 0.0 if insufficient warm-up data.
    pub rsi: f64,
    /// Current volume divided by SMA(volume, 20); 0.0 if insufficient data.
    pub volume_ratio: f64,
    /// SMA(50) trend reference; equals `price` when insufficient data.
    pub trend_sma50: f64,
    /// Unix timestamp (seconds) of the crossover candle.
    pub timestamp: i64,
}
